services:
  mysql:
    image: mysql:8.0
    container_name: smartclinic-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: cms
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  mongo:
    image: mongo:6
    container_name: smartclinic-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    image: smart-clinic-backend
    container_name: smart-clinic
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://smartclinic-mysql:3306/cms
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpass
      SPRING_DATA_MONGODB_URI: mongodb://root:rootpass@smartclinic-mongo:27017/smart_clinic?authSource=admin
    depends_on:
      - mysql
      - mongo

volumes:
  mysql_data:
  mongo_data: